export const stonesList = [
  { id: 1, imgSrc: "/stones/eye-stone.png", staked: false, tier: "highest" },
  {
    id: 2,
    imgSrc: "/stones/GenesisStone3x.png",
    staked: false,
    tier: "common",
  },
  {
    id: 3,
    imgSrc: "/stones/GenesisStone5x.png",
    staked: false,
    tier: "common",
  },
  {
    id: 4,
    imgSrc: "/stones/GenesisStone7x.png",
    staked: false,
    tier: "rare",
  },
  {
    id: 5,
    imgSrc: "/stones/GenesisStone10x.png",
    staked: false,
    tier: "epic",
  },
  {
    id: 6,
    imgSrc: "/stones/GenesisStone15x.png",
    staked: false,
    tier: "rare",
  },
  {
    id: 7,
    imgSrc: "/stones/GenesisStone3x.png",
    staked: false,
    tier: "common",
  },
  {
    id: 8,
    imgSrc: "/stones/GenesisStone3x.png",
    staked: false,
    tier: "common",
  },
  {
    id: 9,
    imgSrc: "/stones/GenesisStone7x.png",
    staked: false,
    tier: "common",
  },
  {
    id: 10,
    imgSrc: "/stones/GenesisStone10x.png",
    staked: false,
    tier: "epic",
  },
  {
    id: 11,
    imgSrc: "/stones/GenesisStone15x.png",
    staked: false,
    tier: "rare",
  },
  {
    id: 12,
    imgSrc: "/stones/GenesisStone5x.png",
    staked: false,
    tier: "common",
  },
  {
    id: 13,
    imgSrc: "/stones/GenesisStone7x.png",
    staked: false,
    tier: "rare",
  },
  {
    id: 14,
    imgSrc: "/stones/GenesisStone3x.png",
    staked: false,
    tier: "common",
  },
  {
    id: 15,
    imgSrc: "/stones/GenesisStone10x.png",
    staked: false,
    tier: "epic",
  },
  {
    id: 16,
    imgSrc: "/stones/GenesisStone15x.png",
    staked: false,
    tier: "rare",
  },
  {
    id: 17,
    imgSrc: "/stones/GenesisStone5x.png",
    staked: false,
    tier: "common",
  },
];
