export const stonesList = [
  {
    id: 1,
    imgSrc: "/imgs/stones/eye-stone.png",
    staked: false,
    tier: "highest",
  },
  {
    id: 2,
    imgSrc: "/imgs/stones/GenesisStone3x.png",
    staked: false,
    tier: "common",
  },
  {
    id: 3,
    imgSrc: "/imgs/stones/GenesisStone5x.png",
    staked: false,
    tier: "common",
  },
  {
    id: 4,
    imgSrc: "/imgs/stones/GenesisStone7x.png",
    staked: false,
    tier: "rare",
  },
  {
    id: 5,
    imgSrc: "/imgs/stones/GenesisStone10x.png",
    staked: false,
    tier: "epic",
  },
  {
    id: 6,
    imgSrc: "/imgs/stones/GenesisStone15x.png",
    staked: false,
    tier: "rare",
  },
  {
    id: 7,
    imgSrc: "/imgs/stones/GenesisStone3x.png",
    staked: false,
    tier: "common",
  },
  {
    id: 8,
    imgSrc: "/imgs/stones/GenesisStone3x.png",
    staked: false,
    tier: "common",
  },
  {
    id: 9,
    imgSrc: "/imgs/stones/GenesisStone7x.png",
    staked: false,
    tier: "common",
  },
  {
    id: 10,
    imgSrc: "/imgs/stones/GenesisStone10x.png",
    staked: false,
    tier: "epic",
  },
  {
    id: 11,
    imgSrc: "/imgs/stones/GenesisStone15x.png",
    staked: false,
    tier: "rare",
  },
  {
    id: 12,
    imgSrc: "/imgs/stones/GenesisStone5x.png",
    staked: false,
    tier: "common",
  },
  {
    id: 13,
    imgSrc: "/imgs/stones/GenesisStone7x.png",
    staked: false,
    tier: "rare",
  },
  {
    id: 14,
    imgSrc: "/imgs/stones/GenesisStone3x.png",
    staked: false,
    tier: "common",
  },
  {
    id: 15,
    imgSrc: "/imgs/stones/GenesisStone10x.png",
    staked: false,
    tier: "epic",
  },
  {
    id: 16,
    imgSrc: "/imgs/stones/GenesisStone15x.png",
    staked: false,
    tier: "rare",
  },
  {
    id: 17,
    imgSrc: "/imgs/stones/GenesisStone5x.png",
    staked: false,
    tier: "common",
  },
];
